application: beflowered
version: 9
runtime: python
api_version: 1

handlers:
- url: /static/css
  static_dir: static/css
  mime_type: text/css

- url: /static/js
  static_dir: static/js
  mime_type: text/javascript

- url: /static/images
  static_dir: static/images
  mime_type: image/png

- url: /favicon\.ico
  static_files: static/favicon.ico
  mime_type: image/ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  mime_type: text/plain
  upload: static/robots.txt  

- url: /admin/remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: always
  
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  secure: always

- url: /event/.*
  script: events.py

- url: /.*
  script: flowered.py
  
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/.svn/.*)|
 (LICENSE)|
 (README)|
 (readme\.txt)|
 )$
