application: beflowered
version: 1
runtime: python
api_version: 1

handlers:

- url: /static/css
  static_dir: static/css
  mime_type: text/css

- url: /static/js
  static_dir: static/js
  mime_type: text/javascript

- url: /static/images
  static_dir: static/images
  mime_type: image/png

- url: /event/.*
  script: events.py

- url: /favicon.ico
  static_files: static/images/favicon.ico
  mime_type: image/ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  mime_type: text/plain
  upload: robots.txt

- url: /.*
  script: flowered.py


